import type { EngineParams, PresetId } from "./types.ts";
import type { ConservativeParams } from "./conservative-types.ts";

const base: EngineParams = {
  latitude: 38.8333,
  longitude: -104.8214,
  altitudeM: 1800,
  speedMs: 0,
  headingDeg: 0,
  antennaHeightM: 2.4,
  antennaLengthM: 2.4,
  groundResistanceOhm: 1.5,
  extraCoilTurns: 100,
  extraCoilRadiusM: 1.257,
  extraCoilHeightM: 2.438,
  loadingCoilH: 0,
  primaryCapacitanceF: 8.1e-8,
  sparkVoltageV: 20000,
  couplingK: 0.12,
  earthGrip: 0.28,
  regenerativeGain: 0.55,
  radiantAreaM2: 1.2,
  weather: "fair",
  mode: "coil",
  starterOn: true,
  starterWatts: 400,
  motorLoadNm: 40,
  etaSpark: 0.72,
  etaRegen: 0.45,
};

export const PRESETS: Record<
  PresetId,
  { name: string; blurb: string; paper: string; params: EngineParams }
> = {
  colorado: {
    name: "Colorado Springs 1899",
    blurb: "Diary extra coil. Confirm spark and Q against the notes.",
    paper: "CSN 14 Dec 1899",
    params: { ...base },
  },
  wardenclyffe: {
    name: "Wardenclyffe 1901",
    blurb: "Earth mode. Cupola + shaft grip. Slow oscillation.",
    paper: "US 1,119,732",
    params: {
      ...base,
      latitude: 40.95,
      longitude: -72.9,
      altitudeM: 40,
      antennaHeightM: 57,
      antennaLengthM: 20,
      extraCoilTurns: 140,
      extraCoilRadiusM: 2.1,
      extraCoilHeightM: 8,
      loadingCoilH: 12,
      primaryCapacitanceF: 1.2e-7,
      sparkVoltageV: 50000,
      couplingK: 0.08,
      earthGrip: 0.85,
      regenerativeGain: 0.7,
      radiantAreaM2: 40,
      mode: "earth",
      starterWatts: 2000,
      motorLoadNm: 80,
      groundResistanceOhm: 0.4,
    },
  },
  car1931: {
    name: "Car receiver 1931",
    blurb: "Pierce-Arrow mapping. Aerial, chassis ground, regen box, AC motor.",
    paper: "787,412 + 381,968",
    params: {
      ...base,
      latitude: 42.8864,
      longitude: -78.8784,
      altitudeM: 180,
      speedMs: 20,
      headingDeg: 90,
      antennaHeightM: 1.85,
      antennaLengthM: 1.83,
      extraCoilTurns: 420,
      extraCoilRadiusM: 0.18,
      extraCoilHeightM: 0.55,
      loadingCoilH: 0.8,
      primaryCapacitanceF: 2.2e-8,
      sparkVoltageV: 8000,
      couplingK: 0.18,
      earthGrip: 0.32,
      regenerativeGain: 0.8,
      radiantAreaM2: 0.4,
      mode: "earth",
      starterWatts: 120,
      motorLoadNm: 18,
      groundResistanceOhm: 8,
      etaSpark: 0.6,
      etaRegen: 0.55,
    },
  },
  honest: {
    name: "Honest ambient",
    blurb: "Grip near zero. Physics-only P_in. Loop gain stays damped.",
    paper: "Maxwell ledger",
    params: {
      ...base,
      latitude: 40.95,
      longitude: -72.9,
      speedMs: 25,
      antennaHeightM: 1.8,
      antennaLengthM: 2,
      extraCoilTurns: 200,
      extraCoilRadiusM: 0.25,
      extraCoilHeightM: 0.6,
      loadingCoilH: 0.2,
      earthGrip: 0.02,
      regenerativeGain: 0.1,
      radiantAreaM2: 0.5,
      mode: "earth",
      starterOn: true,
      starterWatts: 80,
      motorLoadNm: 12,
      groundResistanceOhm: 12,
      couplingK: 0.15,
    },
  },
};

export const PRESET_ORDER: PresetId[] = [
  "colorado",
  "wardenclyffe",
  "car1931",
  "honest",
];

export const DEFAULT_PARAMS: EngineParams = PRESETS.colorado.params;

export const PRESET_CONSERVATIVE_PARAMS: Record<PresetId, Partial<ConservativeParams>> = {
  colorado: {
    primaryCapacitanceF: 8.1e-8,
    primaryInductanceH: 12.34e-6,
    sparkVoltageV: 20000,
    extraCoilTurns: 100,
    extraCoilRadiusM: 1.257,
    extraCoilHeightM: 2.438,
    loadingCoilH: 0,
    antennaHeightM: 2.4,
    groundResistanceOhm: 1.5,
    couplingK: 0.12,
    weather: "fair",
    latitude: 38.8333,
    altitudeM: 1800,
  },
  wardenclyffe: {
    primaryCapacitanceF: 1.2e-7,
    primaryInductanceH: 8.3e-6,
    sparkVoltageV: 50000,
    extraCoilTurns: 140,
    extraCoilRadiusM: 2.1,
    extraCoilHeightM: 8.0,
    loadingCoilH: 12.0,
    antennaHeightM: 57.0,
    groundResistanceOhm: 0.4,
    couplingK: 0.08,
    weather: "fair",
    latitude: 40.95,
    altitudeM: 40,
  },
  car1931: {
    primaryCapacitanceF: 2.2e-8,
    primaryInductanceH: 51e-6,
    sparkVoltageV: 8000,
    extraCoilTurns: 420,
    extraCoilRadiusM: 0.18,
    extraCoilHeightM: 0.55,
    loadingCoilH: 0.8,
    antennaHeightM: 1.85,
    groundResistanceOhm: 8.0,
    couplingK: 0.18,
    weather: "fair",
    latitude: 42.8864,
    altitudeM: 180,
  },
  honest: {
    primaryCapacitanceF: 8.1e-8,
    primaryInductanceH: 40e-6,
    sparkVoltageV: 20000,
    extraCoilTurns: 200,
    extraCoilRadiusM: 0.25,
    extraCoilHeightM: 0.6,
    loadingCoilH: 0.2,
    antennaHeightM: 1.8,
    groundResistanceOhm: 12.0,
    couplingK: 0.15,
    weather: "fair",
    latitude: 40.95,
    altitudeM: 40,
  },
};
